import streamlit as st
import os
import base64

def get_image_base64(image_filename):
    image_path = os.path.join(os.path.dirname(__file__), 'assets', 'images', image_filename)
    if not os.path.exists(image_path):
        name = image_filename.split('.')[0]
        return f"https://ui-avatars.com/api/?name={name}&background=0d1117&color=00ffcc&size=100&rounded=true"
    
    with open(image_path, "rb") as img_file:
        encoded_string = base64.b64encode(img_file.read()).decode()
    
    ext = image_filename.split('.')[-1].lower()
    mime = 'image/jpeg' if ext in ['jpg', 'jpeg'] else 'image/png'
    return f"data:{mime};base64,{encoded_string}"

import streamlit.components.v1 as components

def inject_3d_solar_system():
    # Inject CSS to make the iframe full screen
    st.markdown("""
    <style>
        /* Target the iframe generated by components.html */
        iframe {
            position: fixed !important;
            top: 0 !important;
            left: 0 !important;
            width: 100vw !important;
            height: 100vh !important;
            z-index: -999 !important;
            border: none !important;
            pointer-events: none !important;
        }
    </style>
    """, unsafe_allow_html=True)

    galaxy_js = """
    <style>
        body { margin: 0; padding: 0; overflow: hidden; background: #05050a; }
        canvas { display: block; position: absolute; top: 0; left: 0; width: 100vw; height: 100vh; }
    </style>
    <canvas id="galaxy-canvas"></canvas>
    <script>
        const canvas = document.getElementById('galaxy-canvas');
        const ctx = canvas.getContext('2d', { alpha: false });
        let width, height;

        function resize() {
            width = window.innerWidth;
            height = window.innerHeight;
            canvas.width = width;
            canvas.height = height;
        }
        window.addEventListener('resize', resize);
        resize();

        // Galaxy Configuration
        const numStars = 5000;
        let galaxyRadius = Math.max(width, height) * 0.9;
        if (!galaxyRadius || galaxyRadius < 500) galaxyRadius = 1000;
        
        const stars = [];
        const eventHorizonRadius = 80;

        for (let i = 0; i < numStars; i++) {
            // Logarithmic distribution, but push everything outside the event horizon
            let r = eventHorizonRadius + Math.pow(Math.random(), 2.2) * galaxyRadius; 
            
            // Random angle for vortex
            let angle = Math.random() * Math.PI * 2;
            
            // Z-axis (disc thickness)
            let zSpread = 100 * Math.exp(-(r - eventHorizonRadius) / 200); 
            let z = (Math.random() - 0.5) * zSpread;
            
            // Color selection (Cyan, Magenta, Purple, Pink like the reference)
            const colors = [
                '#00ffff', // Cyan
                '#ff00ff', // Magenta
                '#8a2be2', // BlueViolet
                '#ff1493', // DeepPink
                '#9400d3'  // DarkViolet
            ];
            // Inner stars closer to the burning ring get a warmer tint, outer get the cyan/magenta
            let isInner = r < eventHorizonRadius + 150;
            let baseColor = isInner && Math.random() > 0.5 ? '#ff4500' : colors[Math.floor(Math.random() * colors.length)];
            
            let size = Math.random() * 1.5 + 0.5;
            let alpha = Math.random() * 0.8 + 0.2;
            
            stars.push({
                r: r,
                angle: angle,
                z: z,
                size: size,
                color: baseColor,
                alpha: alpha,
                // Inner stars orbit much faster
                speed: 0.002 + (0.02 * (100 / r))
            });
        }

        let time = 0;

        function animate() {
            // Very dark background
            ctx.fillStyle = '#020205';
            ctx.fillRect(0, 0, width, height);
            
            time += 0.005;
            
            const cx = width / 2;
            const cy = height / 2;
            
            // Dynamic camera rotation (slight 3D tilt)
            let rotX = Math.PI / 3.5; 
            let rotY = time * 0.2; // Spin the whole galaxy
            
            // 1. Draw Burning Orange Accretion Disk Glow
            let diskGlow = ctx.createRadialGradient(cx, cy, eventHorizonRadius, cx, cy, eventHorizonRadius + 200);
            diskGlow.addColorStop(0, 'rgba(255, 100, 0, 0.8)');   // Bright orange burning inside
            diskGlow.addColorStop(0.2, 'rgba(255, 50, 0, 0.4)');  // Deep red/orange
            diskGlow.addColorStop(0.5, 'rgba(128, 0, 255, 0.1)'); // Fading to purple
            diskGlow.addColorStop(1, 'transparent');
            
            ctx.fillStyle = diskGlow;
            
            // Apply 3D transform to the glow to make it an ellipse
            ctx.save();
            ctx.translate(cx, cy);
            ctx.scale(1, Math.cos(rotX)); // Squash it to match 3D tilt
            ctx.translate(-cx, -cy);
            ctx.beginPath();
            ctx.arc(cx, cy, eventHorizonRadius + 200, 0, Math.PI * 2);
            ctx.fill();
            ctx.restore();

            // 2. Draw Stars
            for (let s of stars) {
                s.angle += s.speed;
                
                let x = Math.cos(s.angle) * s.r;
                let y = Math.sin(s.angle) * s.r;
                let z = s.z;
                
                let x1 = x * Math.cos(rotY) - z * Math.sin(rotY);
                let z1 = z * Math.cos(rotY) + x * Math.sin(rotY);
                
                let y2 = y * Math.cos(rotX) - z1 * Math.sin(rotX);
                let z2 = z1 * Math.cos(rotX) + y * Math.sin(rotX);
                
                let scale = 1100 / (1100 + z2);
                if (scale < 0) continue;
                
                let screenX = cx + x1 * scale;
                let screenY = cy + y2 * scale;
                
                ctx.globalAlpha = Math.min(1, s.alpha * scale);
                ctx.fillStyle = s.color;
                
                // Optional: Add glow to inner stars
                if (s.r < eventHorizonRadius + 100) {
                    ctx.shadowBlur = 10;
                    ctx.shadowColor = s.color;
                } else {
                    ctx.shadowBlur = 0;
                }

                ctx.beginPath();
                ctx.arc(screenX, screenY, s.size * scale, 0, Math.PI * 2);
                ctx.fill();
            }
            
            ctx.shadowBlur = 0; // Reset
            
            // 3. Draw The Black Hole (Event Horizon)
            ctx.save();
            ctx.translate(cx, cy);
            ctx.scale(1, Math.cos(rotX)); // Squash the black hole to match perspective
            ctx.translate(-cx, -cy);
            
            // Outer harsh burning ring
            ctx.beginPath();
            ctx.arc(cx, cy, eventHorizonRadius + 2, 0, Math.PI * 2);
            ctx.strokeStyle = 'rgba(255, 150, 0, 0.9)';
            ctx.lineWidth = 4;
            ctx.shadowBlur = 30;
            ctx.shadowColor = '#ff3300';
            ctx.stroke();

            // Inner absolute black void
            ctx.beginPath();
            ctx.arc(cx, cy, eventHorizonRadius, 0, Math.PI * 2);
            ctx.fillStyle = '#000000';
            ctx.shadowBlur = 0; // No glow on the black void
            ctx.fill();
            
            ctx.restore();
            
            requestAnimationFrame(animate);
        }
        animate();
    </script>
    """
    components.html(galaxy_js, height=10, width=10)

def load_css(theme='dark'):
    css_path = os.path.join(os.path.dirname(__file__), 'styles', 'custom.css')
    try:
        with open(css_path, "r") as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
    except FileNotFoundError:
        st.warning("Custom CSS file not found.")
        
    if theme == 'light':
        light_css_path = os.path.join(os.path.dirname(__file__), 'styles', 'light.css')
        try:
            with open(light_css_path, "r") as f:
                st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
        except FileNotFoundError:
            pass
    elif theme == 'pink':
        pink_css_path = os.path.join(os.path.dirname(__file__), 'styles', 'pink.css')
        try:
            with open(pink_css_path, "r") as f:
                st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
        except FileNotFoundError:
            pass

    inject_3d_solar_system()

def back_to_home_button():
    st.markdown('<div style="margin-bottom: 20px;"></div>', unsafe_allow_html=True)
    if st.button("← Back to Home", key=f"back_home_{st.session_state.get('current_page', 'none')}"):
        st.session_state['current_page'] = 'landing'
        st.rerun()

def get_color_for_emotion(emotion):
    emotion = emotion.lower()
    colors = {
        'joy': '#00ffcc',
        'anger': '#ff0055',
        'sadness': '#4d4dff',
        'fear': '#bf00ff',
        'surprise': '#ffcc00',
        'disgust': '#a6ff4d',
        'neutral': '#cccccc'
    }
    return colors.get(emotion, '#ffffff')

def get_color_for_urgency(urgency):
    urgency = urgency.lower()
    colors = {
        'low': '#00ffcc',
        'medium': '#ffcc00',
        'high': '#ff6600',
        'critical': '#ff0055'
    }
    return colors.get(urgency, '#ffffff')
