import streamlit as st
import os
import base64

def get_image_base64(image_filename):
    image_path = os.path.join(os.path.dirname(__file__), 'assets', 'images', image_filename)
    if not os.path.exists(image_path):
        name = image_filename.split('.')[0]
        return f"https://ui-avatars.com/api/?name={name}&background=0d1117&color=00ffcc&size=100&rounded=true"
    
    with open(image_path, "rb") as img_file:
        encoded_string = base64.b64encode(img_file.read()).decode()
    
    ext = image_filename.split('.')[-1].lower()
    mime = 'image/jpeg' if ext in ['jpg', 'jpeg'] else 'image/png'
    return f"data:{mime};base64,{encoded_string}"

import streamlit.components.v1 as components

def inject_3d_solar_system():
    # Inject CSS to make the iframe full screen
    st.markdown("""
    <style>
        /* Target the iframe generated by components.html */
        iframe {
            position: fixed !important;
            top: 0 !important;
            left: 0 !important;
            width: 100vw !important;
            height: 100vh !important;
            z-index: -999 !important;
            border: none !important;
            pointer-events: none !important;
        }
    </style>
    """, unsafe_allow_html=True)

    galaxy_js = """
    <style>
        body { margin: 0; padding: 0; overflow: hidden; background: #020205; }
        canvas { display: block; position: absolute; top: 0; left: 0; width: 100vw; height: 100vh; }
    </style>
    <canvas id="galaxy-canvas"></canvas>
    <script>
        const canvas = document.getElementById('galaxy-canvas');
        const ctx = canvas.getContext('2d', { alpha: false });
        let width, height;

        function resize() {
            width = window.innerWidth;
            height = window.innerHeight;
            canvas.width = width;
            canvas.height = height;
        }
        window.addEventListener('resize', resize);
        resize();

        // Galaxy Configuration
        const numStars = 4500;
        const arms = 5;
        const armSpread = 0.7;
        let galaxyRadius = Math.max(width, height) * 0.8;
        if (!galaxyRadius || galaxyRadius < 500) galaxyRadius = 800; // Fallback
        
        const stars = [];

        // Generate Archimedean Spiral Galaxy
        for (let i = 0; i < numStars; i++) {
            // Logarithmic distribution (dense center, sparse edges)
            let r = Math.pow(Math.random(), 2.5) * galaxyRadius; 
            
            // Archimedean Spiral Math
            let armOffset = (Math.random() - 0.5) * armSpread;
            // Thicker spread at the center, thinner at edges
            armOffset *= (1.5 - r/galaxyRadius);
            
            let armIndex = i % arms;
            // Angle increases with radius to form the spiral
            let angle = (r * 0.008) + (armIndex * (Math.PI * 2 / arms)) + armOffset;
            
            // Z-axis (thickness of the galactic disc)
            let zSpread = 120 * Math.exp(-r / 100); 
            let z = (Math.random() - 0.5) * zSpread;
            
            // Color distribution
            let colorRatio = r / galaxyRadius;
            // Core is bright orange/yellow/white, edges are deep blue/purple
            let rColor = Math.floor(255 - (200 * colorRatio));
            let gColor = Math.floor(220 - (180 * colorRatio));
            let bColor = Math.floor(150 + (105 * colorRatio));
            
            let isNebula = Math.random() > 0.97;
            let size = isNebula ? Math.random() * 2.5 + 1.5 : Math.random() * 1.2 + 0.3;
            let alpha = isNebula ? 0.9 : Math.random() * 0.7 + 0.1;
            
            stars.push({
                r: r,
                angle: angle,
                z: z,
                size: size,
                color: `rgba(${rColor}, ${gColor}, ${bColor}, ${alpha})`,
                speed: 0.001 + (0.008 * (100 / (r + 100))) // Keplerian-like orbits (inner faster)
            });
        }

        let time = 0;

        function animate() {
            // Dark space background
            ctx.fillStyle = '#020205';
            ctx.fillRect(0, 0, width, height);
            
            time += 0.005;
            
            const cx = width / 2;
            const cy = height / 2;
            
            // Dynamic camera rotation
            // Slowly wobble the tilt up and down between 50 and 70 degrees
            let rotX = Math.PI / 2.8 + Math.sin(time * 0.3) * 0.15; 
            // Slowly spin around the entire galaxy
            let rotY = time * 0.15; 
            
            // Draw Galactic Core Glow
            let coreGlow = ctx.createRadialGradient(cx, cy, 0, cx, cy, 250);
            coreGlow.addColorStop(0, 'rgba(255, 220, 180, 0.5)');
            coreGlow.addColorStop(0.3, 'rgba(150, 80, 255, 0.15)');
            coreGlow.addColorStop(1, 'transparent');
            ctx.fillStyle = coreGlow;
            ctx.beginPath();
            ctx.arc(cx, cy, 250, 0, Math.PI * 2);
            ctx.fill();

            for (let s of stars) {
                // Orbital motion
                s.angle += s.speed;
                
                // 2D position in the galactic plane
                let x = Math.cos(s.angle) * s.r;
                let y = Math.sin(s.angle) * s.r;
                let z = s.z;
                
                // 3D Rotation (Y axis) - Galaxy spin
                let x1 = x * Math.cos(rotY) - z * Math.sin(rotY);
                let z1 = z * Math.cos(rotY) + x * Math.sin(rotY);
                
                // 3D Rotation (X axis) - Camera tilt
                let y2 = y * Math.cos(rotX) - z1 * Math.sin(rotX);
                let z2 = z1 * Math.cos(rotX) + y * Math.sin(rotX);
                
                // Perspective Projection
                let scale = 1100 / (1100 + z2);
                if (scale < 0) continue; // Behind camera
                
                let screenX = cx + x1 * scale;
                let screenY = cy + y2 * scale;
                
                // Draw Star
                ctx.fillStyle = s.color;
                ctx.globalAlpha = Math.min(1, scale * 1.2);
                ctx.beginPath();
                ctx.arc(screenX, screenY, s.size * scale, 0, Math.PI * 2);
                ctx.fill();
            }
            
            requestAnimationFrame(animate);
        }
        animate();
    </script>
    """
    components.html(galaxy_js, height=10, width=10)

def load_css(theme='dark'):
    css_path = os.path.join(os.path.dirname(__file__), 'styles', 'custom.css')
    try:
        with open(css_path, "r") as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
    except FileNotFoundError:
        st.warning("Custom CSS file not found.")
        
    if theme == 'light':
        light_css_path = os.path.join(os.path.dirname(__file__), 'styles', 'light.css')
        try:
            with open(light_css_path, "r") as f:
                st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
        except FileNotFoundError:
            pass
    elif theme == 'pink':
        pink_css_path = os.path.join(os.path.dirname(__file__), 'styles', 'pink.css')
        try:
            with open(pink_css_path, "r") as f:
                st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
        except FileNotFoundError:
            pass

    inject_3d_solar_system()

def back_to_home_button():
    st.markdown('<div style="margin-bottom: 20px;"></div>', unsafe_allow_html=True)
    if st.button("← Back to Home", key=f"back_home_{st.session_state.get('current_page', 'none')}"):
        st.session_state['current_page'] = 'landing'
        st.rerun()

def get_color_for_emotion(emotion):
    emotion = emotion.lower()
    colors = {
        'joy': '#00ffcc',
        'anger': '#ff0055',
        'sadness': '#4d4dff',
        'fear': '#bf00ff',
        'surprise': '#ffcc00',
        'disgust': '#a6ff4d',
        'neutral': '#cccccc'
    }
    return colors.get(emotion, '#ffffff')

def get_color_for_urgency(urgency):
    urgency = urgency.lower()
    colors = {
        'low': '#00ffcc',
        'medium': '#ffcc00',
        'high': '#ff6600',
        'critical': '#ff0055'
    }
    return colors.get(urgency, '#ffffff')
