import streamlit as st
import os
import base64

def get_image_base64(image_filename):
    image_path = os.path.join(os.path.dirname(__file__), 'assets', 'images', image_filename)
    if not os.path.exists(image_path):
        name = image_filename.split('.')[0]
        return f"https://ui-avatars.com/api/?name={name}&background=0d1117&color=00ffcc&size=100&rounded=true"
    
    with open(image_path, "rb") as img_file:
        encoded_string = base64.b64encode(img_file.read()).decode()
    
    ext = image_filename.split('.')[-1].lower()
    mime = 'image/jpeg' if ext in ['jpg', 'jpeg'] else 'image/png'
    return f"data:{mime};base64,{encoded_string}"

import streamlit.components.v1 as components

def inject_3d_solar_system():
    # Inject CSS to make the iframe full screen
    st.markdown("""
    <style>
        /* Target the iframe generated by components.html */
        iframe {
            position: fixed !important;
            top: 0 !important;
            left: 0 !important;
            width: 100vw !important;
            height: 100vh !important;
            z-index: -999 !important;
            border: none !important;
            pointer-events: none !important;
        }
    </style>
    """, unsafe_allow_html=True)

    solar_js = """
    <style>
        body { margin: 0; padding: 0; overflow: hidden; background: radial-gradient(circle at center, #0a0e17 0%, #000000 100%); }
        canvas { display: block; position: absolute; top: 0; left: 0; width: 100vw; height: 100vh; }
    </style>
    <canvas id="solar-system"></canvas>
    <script>
        const canvas = document.getElementById('solar-system');
        const ctx = canvas.getContext('2d');
        let width, height;

        function resize() {
            width = window.innerWidth;
            height = window.innerHeight;
            canvas.width = width;
            canvas.height = height;
        }
        window.addEventListener('resize', resize);
        resize();

        // Starfield
        const stars = [];
        for(let i = 0; i < 1500; i++) {
            stars.push({
                x: Math.random() * 3000 - 1500,
                y: Math.random() * 3000 - 1500,
                z: Math.random() * 3000 - 1500,
                r: Math.random() * 1.5,
                alpha: Math.random()
            });
        }

        // Planets data (Realistic relative speeds & beautiful colors)
        const planets = [
            { name: 'Mercury', r: 2.5, d: 70, s: 0.012, angle: Math.random()*Math.PI*2, color: '#a8a8a8' },
            { name: 'Venus',   r: 4.5, d: 110, s: 0.009, angle: Math.random()*Math.PI*2, color: '#e3bb76' },
            { name: 'Earth',   r: 5,   d: 160, s: 0.007, angle: Math.random()*Math.PI*2, color: '#4b95f9' },
            { name: 'Mars',    r: 3.5, d: 210, s: 0.005, angle: Math.random()*Math.PI*2, color: '#e27b58' },
            { name: 'Jupiter', r: 14,  d: 340, s: 0.002, angle: Math.random()*Math.PI*2, color: '#c3a171' },
            { name: 'Saturn',  r: 11,  d: 460, s: 0.0015, angle: Math.random()*Math.PI*2, color: '#ead6b8', ring: true },
            { name: 'Uranus',  r: 8,   d: 570, s: 0.001, angle: Math.random()*Math.PI*2, color: '#4fd0e7' },
            { name: 'Neptune', r: 7.5, d: 680, s: 0.0008, angle: Math.random()*Math.PI*2, color: '#4b70dd' }
        ];

        let time = 0;
        
        function drawSphere(x, y, r, color) {
            ctx.beginPath();
            ctx.arc(x, y, r, 0, Math.PI * 2);
            let grad = ctx.createRadialGradient(x - r*0.3, y - r*0.3, r*0.1, x, y, r);
            grad.addColorStop(0, '#ffffff');
            grad.addColorStop(0.2, color);
            grad.addColorStop(0.8, '#000000');
            ctx.fillStyle = grad;
            ctx.fill();
        }

        function animate() {
            ctx.clearRect(0, 0, width, height);
            time += 1;
            
            const cx = width / 2;
            const cy = height / 2;
            
            // Draw Stars with 3D rotation
            for(let i=0; i<stars.length; i++) {
                let s = stars[i];
                // Rotate galaxy slowly
                let sx = s.x * Math.cos(time*0.0001) - s.z * Math.sin(time*0.0001);
                let sz = s.z * Math.cos(time*0.0001) + s.x * Math.sin(time*0.0001);
                
                let scale = 1000 / (1000 + sz);
                if(scale < 0) continue;
                
                let px = cx + sx * scale;
                let py = cy + s.y * scale;
                
                ctx.globalAlpha = Math.min(1, s.alpha * scale);
                ctx.fillStyle = '#ffffff';
                ctx.beginPath();
                ctx.arc(px, py, s.r * scale, 0, Math.PI*2);
                ctx.fill();
            }
            ctx.globalAlpha = 1;

            // Draw Sun Glow
            ctx.beginPath();
            ctx.arc(cx, cy, 40, 0, Math.PI * 2);
            let sunGrad = ctx.createRadialGradient(cx, cy, 10, cx, cy, 120);
            sunGrad.addColorStop(0, '#ffffff');
            sunGrad.addColorStop(0.1, '#fff4cc');
            sunGrad.addColorStop(0.3, '#ff9900');
            sunGrad.addColorStop(1, 'transparent');
            ctx.fillStyle = sunGrad;
            ctx.fill();

            // Draw Sun Core
            ctx.beginPath();
            ctx.arc(cx, cy, 38, 0, Math.PI * 2);
            let coreGrad = ctx.createRadialGradient(cx-10, cy-10, 5, cx, cy, 38);
            coreGrad.addColorStop(0, '#ffffff');
            coreGrad.addColorStop(0.5, '#ffcc00');
            coreGrad.addColorStop(1, '#ff3300');
            ctx.fillStyle = coreGrad;
            ctx.fill();
            
            const perspectiveTilt = 0.35; // 3D Tilt
            
            // Draw Orbits
            ctx.lineWidth = 1;
            for (let p of planets) {
                ctx.beginPath();
                ctx.ellipse(cx, cy, p.d, p.d * perspectiveTilt, 0, 0, Math.PI * 2);
                ctx.strokeStyle = 'rgba(255, 255, 255, 0.05)';
                ctx.stroke();
            }

            // Calculate Planet 3D Positions
            let renderPlanets = [];
            for(let p of planets) {
                p.angle -= p.s; 
                let px = Math.cos(p.angle) * p.d;
                let pz = Math.sin(p.angle) * p.d;
                renderPlanets.push({...p, px: px, pz: pz});
            }
            // Sort by Z index for proper 3D overlapping
            renderPlanets.sort((a,b) => a.pz - b.pz);

            // Draw Planets
            for (let p of renderPlanets) {
                let scale = 800 / (800 + p.pz);
                let x = cx + p.px * scale;
                let y = cy + (p.pz * perspectiveTilt) * scale;
                let r = Math.max(0.5, p.r * scale);
                
                // Saturn's Back Ring
                if (p.ring && p.pz > 0) {
                    ctx.beginPath();
                    ctx.ellipse(x, y, r * 2.8, r * 0.9, 0, Math.PI, Math.PI * 2);
                    ctx.strokeStyle = 'rgba(234, 214, 184, 0.6)';
                    ctx.lineWidth = r * 0.4;
                    ctx.stroke();
                }
                
                drawSphere(x, y, r, p.color);
                
                // Saturn's Front Ring
                if (p.ring) {
                    ctx.beginPath();
                    // Draw front half if planet is behind, or full ring if planet is in front (handled by z-sort)
                    let start = (p.pz <= 0) ? 0 : 0;
                    let end = (p.pz <= 0) ? Math.PI*2 : Math.PI;
                    ctx.ellipse(x, y, r * 2.8, r * 0.9, 0, start, end);
                    ctx.strokeStyle = 'rgba(234, 214, 184, 0.8)';
                    ctx.lineWidth = r * 0.4;
                    ctx.stroke();
                }
            }
            requestAnimationFrame(animate);
        }
        animate();
    </script>
    """
    components.html(solar_js, height=10, width=10)

def load_css(theme='dark'):
    css_path = os.path.join(os.path.dirname(__file__), 'styles', 'custom.css')
    try:
        with open(css_path, "r") as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
    except FileNotFoundError:
        st.warning("Custom CSS file not found.")
        
    if theme == 'light':
        light_css_path = os.path.join(os.path.dirname(__file__), 'styles', 'light.css')
        try:
            with open(light_css_path, "r") as f:
                st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
        except FileNotFoundError:
            pass
    elif theme == 'pink':
        pink_css_path = os.path.join(os.path.dirname(__file__), 'styles', 'pink.css')
        try:
            with open(pink_css_path, "r") as f:
                st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
        except FileNotFoundError:
            pass

    inject_3d_solar_system()

def back_to_home_button():
    st.markdown('<div style="margin-bottom: 20px;"></div>', unsafe_allow_html=True)
    if st.button("← Back to Home", key=f"back_home_{st.session_state.get('current_page', 'none')}"):
        st.session_state['current_page'] = 'landing'
        st.rerun()

def get_color_for_emotion(emotion):
    emotion = emotion.lower()
    colors = {
        'joy': '#00ffcc',
        'anger': '#ff0055',
        'sadness': '#4d4dff',
        'fear': '#bf00ff',
        'surprise': '#ffcc00',
        'disgust': '#a6ff4d',
        'neutral': '#cccccc'
    }
    return colors.get(emotion, '#ffffff')

def get_color_for_urgency(urgency):
    urgency = urgency.lower()
    colors = {
        'low': '#00ffcc',
        'medium': '#ffcc00',
        'high': '#ff6600',
        'critical': '#ff0055'
    }
    return colors.get(urgency, '#ffffff')
